name: hatarakujikan_app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  modal_bottom_sheet: ^2.0.0
  shared_preferences: ^2.0.5
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  month_picker_dialog: ^0.4.0
  common_utils: ^2.0.2
  location: ^4.1.1
  geocoder: ^0.2.1
  intl: ^0.16.1
dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
